FROM golang:1.22

ENV CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /app

COPY ../go.mod ../go.sum ./

RUN go mod download

COPY ./.. .

RUN go build -o /app/builds/todo_app ./cmd/main.go
